In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)
#e^arr[i]

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([-1.04917892,  0.9766448 ,  1.96555091, -2.90336074,  0.42784415,
       -0.41609893,  1.16699851,  0.45092238,  0.64562941,  0.36084037])

In [9]:
B = np.random.randn(10)
B

array([ 1.15312312,  0.19835567, -0.10514493,  0.16332599, -0.95508265,
       -2.05919169, -0.19306647,  0.1501759 ,  0.91946927, -1.34853975])

In [10]:
#Binary functions
np.add(A,B)

array([ 0.1039442 ,  1.17500048,  1.86040598, -2.74003474, -0.5272385 ,
       -2.47529061,  0.97393204,  0.60109829,  1.56509868, -0.98769937])

In [11]:
np.maximum(A,B)

array([ 1.15312312,  0.9766448 ,  1.96555091,  0.16332599,  0.42784415,
       -0.41609893,  1.16699851,  0.45092238,  0.91946927,  0.36084037])

In [13]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True